import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.goto('/');});
test('suspending audio completes the current recording before the context stops',async({page})=>{
 await page.locator('#record').click();await page.waitForTimeout(350);await page.locator('#power').click();await expect.poll(()=>page.evaluate(()=>studio.engine.ctx.state)).toBe('suspended');await expect(page.locator('.take')).toHaveCount(1);expect(await page.evaluate(()=>studio.tape.recording)).toBe(false);expect(await page.evaluate(()=>studio.tape.takes[0].wet.duration)).toBeGreaterThan(.15);
});
test('a long muted layer does not keep an ended tape transport running',async({page})=>{
 await page.locator('#power').click();await page.evaluate(async()=>{const {engine,tape}=studio,ctx=engine.ctx;const take=(duration,muted)=>({id:String(duration),name:'Test',wet:ctx.createBuffer(1,Math.round(ctx.sampleRate*duration),ctx.sampleRate),dry:null,wetGain:1,dryGain:0,offset:0,rate:1,reverse:false,muted});tape.takes=[take(.15,false),take(4,true)];await tape.play();});await expect.poll(()=>page.evaluate(()=>studio.tape.playing),{timeout:2000}).toBe(false);
});
test('MIDI device removal clears its sustained notes without stopping another input',async({page})=>{
 await page.evaluate(()=>{window.a={id:'a',name:'A'};window.b={id:'b',name:'B'};window.fakeAccess={inputs:new Map([['a',a],['b',b]])};navigator.requestMIDIAccess=async()=>fakeAccess;});await page.locator('#midi').click();await page.waitForFunction(()=>typeof window.a.onmidimessage==='function');await page.evaluate(()=>{a.onmidimessage({data:[144,60,100]});a.onmidimessage({data:[176,64,127]});a.onmidimessage({data:[128,60,0]});b.onmidimessage({data:[144,67,100]});fakeAccess.inputs.delete('a');fakeAccess.onstatechange();});expect(await page.evaluate(()=>[...studio.engine.notes.values()].map(n=>n.note))).toEqual([67]);expect(await page.evaluate(()=>studio.engine.sustain)).toBe(false);await page.evaluate(()=>{b.onmidimessage({data:[128,67,0]});});expect(await page.evaluate(()=>studio.engine.notes.size)).toBe(0);
});
test('session download and reopen restore exact stereo audio, voice stem and patch after refresh',async({page})=>{
 await page.locator('#power').click();await page.evaluate(()=>{const {engine,tape}=studio,ctx=engine.ctx,wet=ctx.createBuffer(2,4,48000),dry=ctx.createBuffer(1,4,44100);wet.copyToChannel(new Float32Array([.25,-.5,.75,0]),0);wet.copyToChannel(new Float32Array([-.25,.5,-.75,0]),1);dry.copyToChannel(new Float32Array([.125,0,-.125,0]),0);tape.takes=[{id:'roundtrip',name:'Session check',wet,dry,wetGain:.8,dryGain:.2,offset:1.2,rate:2,reverse:true,muted:false}];tape.speed=.5;tape.changed();engine.set(Object.hasOwn(engine.params,'moog.cutoff')?'moog.cutoff':'cutoff',777);});
 const promise=page.waitForEvent('download');await page.locator('#save-session').click();const download=await promise,path=await download.path();expect(download.suggestedFilename()).toMatch(/synthsession$/);await page.evaluate(()=>{studio.tape.takes=[];});await page.reload();await expect(page.locator('#recovery-status')).toContainText(/ready|Recovered/);page.once('dialog',d=>d.accept());const chooser=page.waitForEvent('filechooser');await page.locator('#open-session-button').press('Enter');await (await chooser).setFiles(path);await expect(page.locator('#status')).toContainText('Session restored');const state=await page.evaluate(()=>{const {engine,tape}=studio,t=tape.takes[0];return {cutoff:engine.params[Object.hasOwn(engine.params,'moog.cutoff')?'moog.cutoff':'cutoff'],left:[...t.wet.getChannelData(0)],right:[...t.wet.getChannelData(1)],voice:[...t.dry.getChannelData(0)],rate:t.dry.sampleRate,speed:tape.speed,offset:t.offset};});expect(state).toEqual({cutoff:777,left:[.25,-.5,.75,0],right:[-.25,.5,-.75,0],voice:[.125,0,-.125,0],rate:44100,speed:.5,offset:1.2});await expect(page.locator('#speed-readout')).toContainText('0.50');
 await page.locator('#open-session').setInputFiles({name:'bad.synthsession',mimeType:'application/octet-stream',buffer:Buffer.from('invalid session')});await expect(page.locator('#status')).toContainText('not a synth session');expect(await page.evaluate(()=>studio.tape.takes.length)).toBe(1);
});
test('denied microphone permission leaves the control usable and routing intact',async({page})=>{
 await page.evaluate(()=>navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('Microphone denied for test','NotAllowedError');});await page.locator('#mic').click();await expect(page.locator('#status')).toContainText('Microphone denied');await expect(page.locator('#mic')).toBeEnabled();expect(await page.evaluate(()=>studio.engine.micStream)).toBeNull();
});

test('vocoder receives microphone audio, shows analysis, and releases when the mic stops',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.locator('#preset').selectOption('17 / Microphone vocoder');await page.locator('#power').click();await page.evaluate(()=>{const ctx=studio.engine.ctx,osc=ctx.createOscillator(),gain=ctx.createGain(),dest=ctx.createMediaStreamDestination();osc.type='sawtooth';osc.frequency.value=175;gain.gain.value=.15;osc.connect(gain).connect(dest);osc.start();navigator.mediaDevices.getUserMedia=async()=>dest.stream;});await page.locator('#mic').click();await expect.poll(()=>page.locator('#out-meter').evaluate(el=>el.value)).toBeGreaterThan(.005);await expect.poll(()=>page.locator('[data-band]').evaluateAll(els=>Math.max(...els.map(el=>el.value)))).toBeGreaterThan(.01);await page.locator('#mic').click();await expect.poll(()=>page.locator('#out-meter').evaluate(el=>el.value),{timeout:6000}).toBeLessThan(.0001);expect(errors).toEqual([]);
});
test('spectral controls and session buttons stay accessible at four screen widths',async({page})=>{
 for(const width of [390,768,1000,1600]){await page.setViewportSize({width,height:1000});await page.locator('#cab-fx').scrollIntoViewIfNeeded();await expect(page.locator('[data-param="fx.monitor"]')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);await expect(page.locator('#save-session')).toBeAttached();}await page.locator('#cab-fx').screenshot({path:'test-results/spectral-panel.png'});
});

test('output meter includes tape playback, follows master gain, and clears on suspension',async({page})=>{
 await page.locator('#power').click();await page.evaluate(async()=>{const {engine,tape}=studio,ctx=engine.ctx,b=ctx.createBuffer(1,ctx.sampleRate*3,ctx.sampleRate);for(let i=0;i<b.length;i++)b.getChannelData(0)[i]=.2*Math.sin(i/ctx.sampleRate*Math.PI*2*220);tape.takes=[{id:'meter',name:'Meter',wet:b,dry:null,wetGain:1,dryGain:0,offset:0,rate:1,reverse:false,muted:false}];await tape.play();});await expect.poll(()=>page.locator('#out-meter').evaluate(el=>el.value)).toBeGreaterThan(.02);await page.evaluate(()=>studio.engine.set('master',0));await expect.poll(()=>page.locator('#out-meter').evaluate(el=>el.value)).toBeLessThan(.0001);await page.locator('#power').click();await expect(page.locator('#out-meter')).toHaveJSProperty('value',0);expect(await page.evaluate(()=>studio.engine.micAnalyser.fftSize)).toBe(await page.evaluate(()=>studio.engine.analyser.fftSize));
});
