import {test,expect} from '@playwright/test';
const action=(page,name)=>page.locator('#patch-library [data-action="'+name+'"]');
test.beforeEach(async({page})=>{await page.goto('/');await page.locator('#browse-library').click();});
test('search, combined filters, paging and favorites survive a refresh',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));expect(await page.locator('.library-result').count()).toBe(24);await action(page,'next').click();await expect(page.locator('#library-page')).toContainText('Page 2');await page.locator('#library-search').fill('ring');await page.locator('#library-category').selectOption('Voice');await expect(page.locator('.library-result').first()).toBeVisible();await action(page,'favorite').click();const name=await page.locator('#library-name').textContent();await page.reload();await page.locator('#browse-library').click();await page.locator('#library-scope').selectOption('favorites');await expect(page.locator('.library-result')).toHaveCount(1);await expect(page.locator('#library-name')).toHaveText(name);await action(page,'favorite').click();await expect(page.locator('#library-name')).toHaveText('No matching patches');expect(errors).toEqual([]);
});
test('preview uses rendered audio, leaves the current patch intact and stops on close',async({page})=>{
 await page.evaluate(()=>{window.previewStarts=[];window.previewStops=0;const start=AudioBufferSourceNode.prototype.start,stop=AudioBufferSourceNode.prototype.stop;AudioBufferSourceNode.prototype.start=function(...args){previewStarts.push({frames:this.buffer.length,peak:this.buffer.getChannelData(0).reduce((p,v)=>Math.max(p,Math.abs(v)),0)});return start.apply(this,args);};AudioBufferSourceNode.prototype.stop=function(...args){previewStops++;return stop.apply(this,args);};});
 const snapshot=()=>page.evaluate(()=>JSON.stringify({params:studio.engine.params,routes:studio.engine.routes,performance:studio.engine.state?.performance}));const before=await snapshot();await page.locator('#library-search').fill('rubber pulse');await action(page,'preview').click();await expect.poll(()=>page.evaluate(()=>previewStarts.length),{timeout:30000}).toBe(1);expect(await page.evaluate(()=>previewStarts[0].peak)).toBeGreaterThan(.001);expect(await snapshot()).toBe(before);await action(page,'close').click();expect(await page.evaluate(()=>previewStops)).toBeGreaterThan(0);expect(await snapshot()).toBe(before);
});
test('save, edit notes, export, duplicate import and delete preserve existing memories',async({page})=>{
 await page.locator('#library-save summary').click();await page.locator('#library-save-name').fill('My library reed');await page.locator('#library-save-category').fill('Reeds');await page.locator('#library-save-tags').fill('soft, live');await page.locator('#library-save-description').fill('A saved <reed> & its cables.');await page.locator('#library-save-submit').click();await expect(page.locator('#library-name')).toHaveText('My library reed');await expect(page.locator('#library-description')).toHaveText('A saved <reed> & its cables.');
 await action(page,'edit').click();await page.locator('#library-save-name').fill('My renamed reed');await page.locator('#library-save-submit').click();await expect(page.locator('#library-name')).toHaveText('My renamed reed');const pending=page.waitForEvent('download');await action(page,'export').click();const file=await (await pending).path();await page.locator('#library-import').setInputFiles(file);await expect(page.locator('#library-status')).toContainText('Imported 1 patches');await expect(page.locator('.library-result')).toHaveCount(2);await expect(page.locator('#library-results')).toContainText('My renamed reed (2)');await page.reload();await page.locator('#browse-library').click();await page.locator('#library-scope').selectOption('saved');await expect(page.locator('.library-result')).toHaveCount(2);await expect(page.locator('#library-description')).toHaveText('A saved <reed> & its cables.');page.once('dialog',d=>d.accept());await action(page,'delete').click();await expect(page.locator('.library-result')).toHaveCount(1);
});
test('invalid banks and storage failure leave patch memory unchanged',async({page})=>{
 const before=await page.evaluate(()=>JSON.stringify(localStorage));await page.locator('#library-import').setInputFiles({name:'broken.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({format:'synth-patch-bank',version:1,studio:'unknown',patches:[{name:'bad',patch:{params:{},routes:{}}}]}))});await expect(page.locator('#library-status')).toContainText('different studio');expect(await page.evaluate(()=>JSON.stringify(localStorage))).toBe(before);
 await page.evaluate(()=>Storage.prototype.setItem=()=>{throw new Error('Storage unavailable for test');});await page.locator('#library-save summary').click();await page.locator('#library-save-name').fill('Unstored');await page.locator('#library-save-submit').click();await expect(page.locator('#library-status')).toContainText('Storage unavailable');await page.locator('#library-scope').selectOption('saved');await expect(page.locator('.library-result')).toHaveCount(0);
});
test('library fits phone and desktop screens; typing shortcuts never starts the synth',async({page})=>{
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});expect(await page.locator('#patch-library').evaluate(el=>el.scrollWidth-el.clientWidth)).toBeLessThanOrEqual(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);if([390,1440].includes(width))await page.locator('#patch-library').screenshot({path:'test-results/library-'+width+'.png'});}
 await action(page,'preview').focus();await page.keyboard.press('a');expect(await page.evaluate(()=>!!studio.engine.ctx)).toBe(false);await page.keyboard.press('Escape');await expect(page.locator('#patch-library')).not.toBeVisible();await expect(page.locator('#browse-library')).toBeFocused();
});
