import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.goto('/');});
async function settings(page){await page.locator('#performance-bars').selectOption('1');await page.locator('#performance-count').selectOption('0');await page.locator('#performance-tempo').fill('220');await page.locator('#performance-tempo').press('Tab');}
test('capture keys, sustain and a control sweep; edit, quantize, replay actual audio and stop',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await settings(page);await page.locator('#performance-record').click();await page.waitForTimeout(150);
 await page.evaluate(()=>{studio.engine.on(60,.8,'test');studio.engine.set('moog.cutoff',500);studio.engine.sustainPedal(true);studio.engine.off('test');});await page.waitForTimeout(150);await page.evaluate(()=>{studio.engine.set('moog.cutoff',1500);studio.engine.sustainPedal(false);});
 await expect(page.locator('#performance-record')).toBeEnabled({timeout:4000});expect(await page.evaluate(()=>studio.engine.state.performance.notes.length)).toBe(1);expect(await page.evaluate(()=>studio.engine.state.performance.notes[0].length)).toBeGreaterThan(.3);expect(await page.evaluate(()=>studio.engine.state.performance.lanes['moog.cutoff'].length)).toBeGreaterThan(1);
 await page.locator('.performance-editor summary').click();await page.locator('[aria-label="Note 1 note"]').fill('67');await page.locator('[aria-label="Note 1 note"]').press('Tab');await page.locator('#performance-quantize').click();expect(await page.evaluate(()=>studio.engine.state.performance.notes[0].at% .25)).toBe(0);
 await page.locator('#performance-click').uncheck();await page.locator('#performance-play').click();await expect.poll(()=>page.locator('#out-meter').evaluate(el=>el.value)).toBeGreaterThan(.001);await expect(page.locator('#tempo')).toBeDisabled();await page.locator('#performance-stop').click();await expect(page.locator('#tempo')).toBeEnabled();await expect(page.locator('#performance-position')).toHaveText('STOPPED');await expect.poll(()=>page.locator('#out-meter').evaluate(el=>el.value),{timeout:5000}).toBeLessThan(.0001);expect(errors).toEqual([]);
});
test('count-in click is audible on the monitor but excluded from tape and no old notes replay while recording',async({page})=>{
 await settings(page);await page.locator('#performance-count').selectOption('8');await page.locator('#performance-tempo').fill('120');await page.locator('#performance-tempo').press('Tab');await page.locator('.performance-editor summary').click();await page.locator('#performance-add').click();await page.locator('#record').click();await page.locator('#performance-record').click();await expect(page.locator('#performance-position')).toContainText('COUNT IN');await expect.poll(()=>page.locator('#out-meter').evaluate(el=>el.value),{intervals:[10,20,30],timeout:1500}).toBeGreaterThan(.002);await page.locator('#panic').click();await page.locator('#tape-stop').click();await expect(page.locator('.take')).toHaveCount(1);expect(await page.evaluate(()=>studio.engine.state.performance.notes.length)).toBe(1);expect(await page.evaluate(()=>studio.tape.takes[0].wet.getChannelData(0).reduce((m,v)=>Math.max(m,Math.abs(v)),0))).toBeLessThan(.000001);
});
test('MIDI learn maps device/channel/controller, preserves sustain, persists and removes',async({page})=>{
 const mock=()=>{window.device={id:'test-controller',name:'Studio faders'};navigator.requestMIDIAccess=async()=>({inputs:new Map([[device.id,device]])});};await page.evaluate(mock);await page.locator('#midi-learn-panel summary').click();await page.locator('#learn-target').selectOption('moog.cutoff');await page.locator('#midi-learn').click();await expect(page.locator('#midi-learn')).toHaveAttribute('aria-pressed','true');await page.evaluate(()=>device.onmidimessage({data:[177,74,10]}));await expect(page.locator('#midi-mappings')).toContainText('Ch 2 · CC 74');await page.evaluate(()=>device.onmidimessage({data:[177,74,127]}));expect(await page.evaluate(()=>studio.engine.params['moog.cutoff'])).toBe(14000);await page.evaluate(()=>device.onmidimessage({data:[176,74,0]}));expect(await page.evaluate(()=>studio.engine.params['moog.cutoff'])).toBe(14000);
 await page.reload();await page.evaluate(mock);await page.locator('#midi').click();await page.waitForFunction(()=>typeof device.onmidimessage==='function');await page.evaluate(()=>device.onmidimessage({data:[177,74,0]}));expect(await page.evaluate(()=>studio.engine.params['moog.cutoff'])).toBe(30);await page.locator('#midi-learn-panel summary').click();await page.locator('#midi-mappings button').click();await expect(page.locator('#midi-mappings')).toBeEmpty();await page.evaluate(()=>{device.onmidimessage({data:[176,64,127]});});expect(await page.evaluate(()=>studio.engine.sustain)).toBe(true);
});
test('patch undo restores a cable and loop, redo works, and text input keeps native undo',async({page})=>{
 await page.locator('#route-source').selectOption('bridge.mic');await page.locator('#route-dest').selectOption('moog.audio');await page.locator('#connect-route').click();await expect(page.locator('#patch-undo')).toBeEnabled();await page.locator('#patch-undo').click();expect(await page.evaluate(()=>studio.engine.routes['moog.audio'])).toBe('arp.v2pulse');await page.locator('#patch-redo').click();expect(await page.evaluate(()=>studio.engine.routes['moog.audio'])).toBe('bridge.mic');
 await page.locator('.performance-editor summary').click();await page.locator('#performance-add').click();await page.waitForTimeout(400);await page.locator('#performance-clear').click();await page.waitForTimeout(400);await page.locator('#patch-undo').click();expect(await page.evaluate(()=>studio.engine.state.performance.notes.length)).toBe(1);await page.locator('[aria-label="Note 1 note"]').focus();await page.keyboard.press('Control+z');expect(await page.evaluate(()=>studio.engine.state.performance.notes.length)).toBe(1);
});
test('performance loop exports and imports with patch JSON and fits small screens',async({page})=>{
 await page.locator('.performance-editor summary').click();await page.locator('#performance-add').click();const waiting=page.waitForEvent('download');await page.locator('#export-patch').click();const path=await (await waiting).path();await page.locator('#performance-clear').click();await page.locator('#import-patch').setInputFiles(path);await expect(page.locator('#performance-summary')).toContainText('1 note');for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:1000});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);}await page.setViewportSize({width:390,height:1000});await page.locator('#performance-memory').screenshot({path:'test-results/performance-mobile.png'});
});

test('factory patch changes keep the phrase and saving during capture completes its notes',async({page})=>{
 await settings(page);await page.locator('#performance-record').click();await page.waitForTimeout(150);await page.evaluate(()=>studio.engine.on(64,.9,'capture'));await page.waitForTimeout(180);
 const waiting=page.waitForEvent('download');await page.locator('#export-patch').click();const path=await (await waiting).path();expect(await page.evaluate(()=>studio.performanceUI.mode)).toBeNull();expect(await page.evaluate(()=>studio.engine.state.performance.notes.length)).toBe(1);await page.evaluate(()=>studio.engine.off('capture'));
 await page.locator('#preset').selectOption({label:'02 / West coast cycles'});expect(await page.evaluate(()=>studio.engine.state.performance.notes.length)).toBe(1);await page.locator('#import-patch').setInputFiles(path);expect(await page.evaluate(()=>studio.engine.state.performance.notes[0].note)).toBe(64);
});

test('recording preserves note starts and dense automation even when visual meter messages are delayed',async({page})=>{
 await page.locator('#power').click();await expect(page.locator('#power')).toHaveAttribute('aria-pressed','true');await page.evaluate(()=>studio.engine.synth.port.onmessage=null);await page.locator('#performance-count').selectOption('0');await page.locator('#performance-record').click();await expect(page.locator('#performance-record')).toHaveAttribute('aria-pressed','true');await page.waitForTimeout(180);
 await page.evaluate(async()=>{studio.engine.on(65,.7,'late');for(let i=0;i<25;i++){studio.engine.set('moog.cutoff',300+i*40);await new Promise(resolve=>setTimeout(resolve,5));}studio.engine.off('late');});await page.locator('#performance-stop').click();const clip=await page.evaluate(()=>studio.engine.state.performance);expect(clip.notes).toHaveLength(1);expect(clip.notes[0].at).toBeGreaterThan(.1);expect(clip.lanes['moog.cutoff'].length).toBeGreaterThan(4);
});
