import {test,expect} from '@playwright/test';
test('autosave restores controls, notes, completed recordings and tape edits without starting audio',async({page})=>{await page.goto('/');await expect(page.locator('#recovery-status')).toContainText('ready');await page.locator('#power').click();await page.evaluate(()=>{const e=studio.engine;e.set(e.params['moog.cutoff']!==undefined?'moog.cutoff':'cutoff',789);e.state.performance.notes=[{note:63,at:0,length:1,velocity:.7}];e.configure();});await page.locator('#record').click();await page.keyboard.down('a');await page.waitForTimeout(350);await page.keyboard.up('a');await page.locator('#tape-stop').click();await expect(page.locator('.take')).toHaveCount(1);await page.evaluate(()=>{studio.tape.takes[0].fadeIn=.02;studio.tape.exportFormat=32;});await page.locator('#recovery-save').click();await expect(page.locator('#recovery-status')).toContainText('saved locally');page.once('dialog',d=>d.accept());await page.reload();await expect(page.locator('#recovery-status')).toContainText('Recovered patch');expect(await page.evaluate(()=>studio.engine.params['moog.cutoff']??studio.engine.params.cutoff)).toBe(789);expect(await page.evaluate(()=>studio.engine.state.performance.notes.length)).toBe(1);expect(await page.evaluate(()=>studio.tape.takes[0].fadeIn)).toBe(.02);expect(await page.evaluate(()=>studio.engine.ctx?.state||'unstarted')).toBe('unstarted');await expect(page.locator('#wav-format')).toHaveValue('32');});
test('recording journal recovers an unfinished take after a renderer crash',async({page,context,baseURL})=>{await page.goto('/');await expect(page.locator('#recovery-status')).toContainText('ready');await page.locator('#record').click();await page.keyboard.down('a');await page.waitForTimeout(600);await page.evaluate(()=>studio.engine.recovery.flush());const cdp=await context.newCDPSession(page);const crashed=page.waitForEvent('crash');void cdp.send('Page.crash').catch(()=>{});await crashed;await page.close().catch(()=>{});const restored=await context.newPage();await restored.goto(baseURL);await expect(restored.locator('#recovery-status')).toContainText(/Recovered patch|saved locally/);await expect(restored.locator('.take')).toHaveCount(1);expect(await restored.evaluate(()=>studio.tape.takes[0].wet.duration)).toBeGreaterThan(.3);expect(await restored.evaluate(()=>studio.tape.takes[0].wet.getChannelData(0).some(v=>Math.abs(v)>.001))).toBe(true);await restored.close();});
test('a second tab cannot overwrite the recovery owner',async({page,context,baseURL})=>{await page.goto('/');await expect(page.locator('#recovery-status')).toContainText('ready');const second=await context.newPage();await second.goto(baseURL);await expect(second.locator('#recovery-status')).toContainText('read-only');await expect(second.locator('#recovery-save')).toBeDisabled();await second.close();});

test('saved status waits for the newest checkpoint when saves overlap',async({page})=>{
 await page.goto('/');await expect(page.locator('#recovery-status')).toContainText('ready');
 await page.evaluate(async()=>{const e=studio.engine;await e.recovery.save();const store=e.recovery.store,checkpoint=store.checkpoint.bind(store);window.releaseCheckpoints=[];store.checkpoint=async(...args)=>{await checkpoint(...args);await new Promise(resolve=>releaseCheckpoints.push(resolve));};window.firstSave=e.recovery.save();});
 await expect.poll(()=>page.evaluate(()=>releaseCheckpoints.length)).toBe(1);
 await page.evaluate(()=>{const e=studio.engine;e.set(e.params['moog.cutoff']!==undefined?'moog.cutoff':'cutoff',876);window.secondSave=e.recovery.save();});
 await expect.poll(()=>page.evaluate(()=>releaseCheckpoints.length)).toBe(2);
 await page.evaluate(async()=>{releaseCheckpoints[0]();await firstSave;});await expect(page.locator('#recovery-status')).toHaveText('Saving recovery…');
 await page.evaluate(async()=>{releaseCheckpoints[1]();await secondSave;});await expect(page.locator('#recovery-status')).toContainText('saved locally');
 await page.reload();await expect(page.locator('#recovery-status')).toContainText('Recovered patch');expect(await page.evaluate(()=>studio.engine.params['moog.cutoff']??studio.engine.params.cutoff)).toBe(876);
});
