import test from 'node:test';
import assert from 'node:assert/strict';
import {encodeWav} from '../public/wav.js';
import {TapePlaybackCore,tapeDuration} from '../public/tape-core.js';
const take=(data,rate=48000)=>({id:'one',wet:{rate,channels:[data]},dry:null,wetGain:1,dryGain:0,rate:1,offset:0,muted:false,reverse:false});
test('24-bit PCM and float WAV retain precision, headers and sample counts',async()=>{const samples=new Float32Array([-.5,0,.25,1.25]);for(const bits of [16,24,32]){const v=new DataView(await (encodeWav([samples],48000,bits)).arrayBuffer());assert.equal(v.getUint16(34,true),bits);assert.equal(v.getUint16(20,true),bits===32?3:1);assert.equal(v.getUint32(28,true),48000*bits/8);if(bits===32){assert.equal(v.getFloat32(56,true),-.5);assert.equal(v.getFloat32(68,true),1.25);}else if(bits===24)assert.equal(v.getUint8(44),0);}});
test('tape repeats without a callback gap over 1000 short loops',()=>{const core=new TapePlaybackCore(48000);core.configure([take(new Float32Array(480).fill(.3))],{loop:true,saturation:0,wow:0,flutter:0});core.start();for(let i=0;i<480000;i++){const out=core.tick(i);if(i>10)assert.ok(out[0]>.29,'audio present at '+i);}assert.ok(core.cycle>=998);});
test('trims, fades, offsets, reversal and rate determine the rendered region without altering the source',()=>{const data=Float32Array.from({length:48000},(_,i)=>i/48000),t={...take(data),trimStart:.25,trimEnd:.75,fadeIn:.05,fadeOut:.05,offset:.1};assert.equal(tapeDuration([t],{speed:2}),.35);const core=new TapePlaybackCore();core.configure([t],{speed:1,saturation:0});core.start();assert.equal(core.tick(0)[0],0);for(let i=1;i<24000;i++)core.tick(i);assert.ok(core.out[0]>.5&&core.out[0]<.7);assert.equal(data[24000],.5);core.configure([{...t,reverse:true}],{});assert.ok(Number.isFinite(core.tick(24000)[0]));});
test('scheduled tape starts on the requested audio frame and updates speed without restarting',()=>{const core=new TapePlaybackCore();core.configure([take(new Float32Array(4800).fill(.2))],{speed:1});core.start(128);for(let i=0;i<128;i++)assert.equal(core.tick(i)[0],0);assert.ok(core.tick(128)[0]>.1);const position=core.position;core.configure(null,{speed:2});assert.equal(core.position,position);});

test('quad WAV declares front and rear speaker channels with interleaved float samples',async()=>{const channels=[.1,.2,.3,.4].map(x=>new Float32Array([x,x]));const v=new DataView(await encodeWav(channels,48000,32).arrayBuffer());assert.equal(v.getUint16(20,true),65534);assert.equal(v.getUint16(22,true),4);assert.equal(v.getUint32(40,true),0x33);assert.equal(v.getUint32(44,true),3);assert.equal(v.getUint32(68,true),2);assert.equal(v.getUint32(76,true),32);for(let c=0;c<4;c++)assert.equal(v.getFloat32(80+c*4,true),channels[c][0]);});
